/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary
        primary: "#021064",
        "on-primary": "#ffffff",
        "primary-container": "#1e2a78",
        "on-primary-container": "#8a95e9",
        "primary-fixed": "#dfe0ff",
        "primary-fixed-dim": "#bcc3ff",
        "on-primary-fixed": "#000d60",
        "on-primary-fixed-variant": "#343f8d",
        // Secondary
        secondary: "#505a99",
        "on-secondary": "#ffffff",
        "secondary-container": "#adb7fd",
        "on-secondary-container": "#3c4684",
        "secondary-fixed": "#dee0ff",
        "secondary-fixed-dim": "#bbc3ff",
        "on-secondary-fixed": "#071352",
        "on-secondary-fixed-variant": "#38427f",
        // Tertiary
        tertiary: "#391100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5b2000",
        "on-tertiary-container": "#dc845b",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb595",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#753311",
        // Error
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // Surface & Background
        surface: "#fbf8ff",
        "on-surface": "#1b1b20",
        "surface-variant": "#e4e1e9",
        "on-surface-variant": "#454651",
        "surface-bright": "#fbf8ff",
        "surface-dim": "#dbd9e0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fa",
        "surface-container": "#efedf4",
        "surface-container-high": "#e9e7ee",
        "surface-container-highest": "#e4e1e9",
        background: "#fbf8ff",
        "on-background": "#1b1b20",
        // Misc
        outline: "#767682",
        "outline-variant": "#c6c5d3",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#f2eff7",
        "inverse-primary": "#bcc3ff",
        "surface-tint": "#4c58a6",
      },
      fontFamily: {
        sans: ['"Public Sans"', "Arial", "Helvetica", "sans-serif"],
        "headline-md": ['"Public Sans"', "sans-serif"],
        "label-bold": ['"Public Sans"', "sans-serif"],
        "body-sm": ['"Public Sans"', "sans-serif"],
        "nav-item": ['"Public Sans"', "sans-serif"],
        "display-lg": ['"Public Sans"', "sans-serif"],
        "body-base": ['"Public Sans"', "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "nav-item": ["15px", { lineHeight: "1", letterSpacing: "0", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
      spacing: {
        "card-padding": "24px",
        "dot-pattern-size": "20px",
        "sidebar-width": "280px",
        gutter: "24px",
        "container-max": "1440px",
        "nav-item-margin": "12px",
      },
    },
  },
  plugins: [],
}